# Site settings
title: Filip Bártek
email: filip.bartek@hotmail.com
url: "http://filipbartek.github.io" # the base hostname & protocol for your site
github_username: filipbartek
repository: filipbartek/filipbartek.github.io

linkedin_username: filipbartek
topcoder_username: filip.bartek
soundcloud_permalink: filip-bartek

exclude: [README.md]

plugins:
  - jekyll-sitemap
